# 標準の規約＋Rails固有の規約を有効にする
require:
  - rubocop-rails

# 特定のLintチェックをオフにする
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false

#以下にはrubocopで検証したくないフォルダを指定
AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'